name: 'PR title Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - labeled
      - unlabeled
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # This job ensure the users always received a feedback
  check-pr-title:
    if: contains(github.event.pull_request.labels.*.name, 'skip-pr-title-check') == false
    name: Validate Hasura PR title
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title against Hasura conventional commit
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(?<type>fix|feat|chore|ci|refactor|test)\(((?<systemPart>console|hge|lux|docs|infra|website)(,)?){1,4}\)(?<breakingChangeFlag>!)?: (?<prTitle>.*)$'
          flags: 'gm'
          error: 'The PR title do not match the expected format, check out this playground https://regex101.com/r/VyZRuo/1 to test your PR title. If you really need your PR title is accepted as is, please add the `skip-pr-title-check` and leave a comment in the PR explaining why you skipped it'
          excludeDescription: 'true' # Only the title of the PR must be checked
